# Generated by Django 3.0.6 on 2020-07-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kejas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mykeja',
            name='more_property_images',
            field=models.ImageField(blank=True, upload_to='media_root'),
        ),
        migrations.AlterField(
            model_name='mykeja',
            name='property_image',
            field=models.ImageField(blank=True, upload_to='media_root'),
        ),
    ]
