# Generated by Django 3.0.6 on 2020-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kejas', '0002_auto_20200719_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mykeja',
            name='more_property_images',
            field=models.ImageField(blank=True, upload_to='keja_pics'),
        ),
    ]
