# Generated by Django 3.0.6 on 2020-07-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kejas', '0004_auto_20200721_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mykeja',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
