# Generated by Django 3.0.6 on 2020-07-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kejas', '0005_auto_20200723_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mykeja',
            name='more_property_images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mykeja',
            name='property_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
